node.override[:node_type] = "slave_node"
node.override[:hostname_] = "cosmosslave2-gi"
include_recipe "cosmos::uninstall_hdfs_datanode"
include_recipe "cosmos::uninstall_mapreduce_tasktracker"
#include_recipe "java::oracle"
include_recipe "cosmos::install_java"
include_recipe "cosmos::install_hdfs_datanode"
include_recipe "cosmos::install_mapreduce_tasktracker"
include_recipe "cosmos_slave_node::0.9.0_start"
