name             'iotDiscovery'
maintainer       'UNIVERSITY OF SURREY'
maintainer_email 't.elsaleh@surrey.ac.uk'
license          'All rights reserved'
description      'Installs/Configures iotDiscovery'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
#depends          'java'
#depends          'mysql'
#depends          'tomcat'
supports         'ubuntu', '>= 14.04'
