DROP FUNCTION IF EXISTS inet6_ntop;
DROP FUNCTION IF EXISTS inet6_pton;
DROP FUNCTION IF EXISTS inet6_lookup;
DROP FUNCTION IF EXISTS inet6_rlookup;
DROP FUNCTION IF EXISTS inet6_mask;
CREATE FUNCTION inet6_ntop RETURNS STRING SONAME "mysql_udf_ipv6.so";
CREATE FUNCTION inet6_pton RETURNS STRING SONAME "mysql_udf_ipv6.so";
CREATE FUNCTION inet6_lookup RETURNS STRING SONAME "mysql_udf_ipv6.so";
CREATE FUNCTION inet6_rlookup RETURNS STRING SONAME "mysql_udf_ipv6.so";
CREATE FUNCTION inet6_mask RETURNS STRING SONAME "mysql_udf_ipv6.so";

